USE UWBOX
GO

--GET TENOR TYPE (Must Migration)
select CODE, DESCR from PR_TENOR_TYPE
GO

--GET DDL Product Group (Must Migration)
select CODE, DESCR from PARAM_PRODUCT_GROUP order by 2
GO

--GET List Premium Rate
select CODE, DESCR from PARAM_PREMIUM_RATE_MASTER 
where DESCR like '%%' and PRODUCT_GROUP = 'GTL' order by 2
GO

--SAVE FIRST PREMIUM RATE [SP_PARAM_PREMIUM_RATE_MASTER_UPSERT]
--REDIRECT AFTER SAVE
select CODE, DESCR, TENOR_CODE, PRODUCT_GROUP from PARAM_PREMIUM_RATE_MASTER where CODE = '20230228165222963'
GO

--DOWNLOAD TEMPLATE 
EXEC RPT_PARAM_PREMIUM_RATE '20230228165222963'

--GET LIST PREMIUM RATE DETAIL [SP_PARAM_PREMIUM_RATE_DETAIL]
SELECT * FROM PARAM_PREMIUM_RATE_DETAIL
GO

--SP Ketika upload file [SP_PARAM_PREMIUM_RATE_DETAIL_UPSERT]
SP_PARAM_PREMIUM_RATE_DETAIL_UPSERT