CREATE PROCEDURE [dbo].[SP_PARAM_PREMIUM_RATE_MASTER_UPSERT]
@CODE	varchar(30),
@DESCR	varchar(100),
@TENOR_CODE	varchar(10),
@PRODUCT_GROUP varchar(10),
@USERBY	varchar(50)
AS

if @CODE is null
begin
	
	set @CODE = dbo.UFN_GET_NEWID()
	insert into PARAM_PREMIUM_RATE_MASTER select
	CODE			= @CODE,
	DESCR			= @DESCR,
	TENOR_CODE		= @TENOR_CODE,
	PRODUCT_GROUP	= @PRODUCT_GROUP,
	STAT			= 1,
	CREATEBY		= @USERBY,
	CREATEDATE		= GETDATE(),
	LASTCHANGEBY	= @USERBY,
	LASTCHANGEDATE	= GETDATE()

end else
begin

	update PARAM_PREMIUM_RATE_MASTER set
	DESCR			= @DESCR,
	TENOR_CODE		= @TENOR_CODE,
	PRODUCT_GROUP	= @PRODUCT_GROUP,
	LASTCHANGEBY	= @USERBY,
	LASTCHANGEDATE	= GETDATE()
	where
	CODE			= @CODE

end

select CODE = @CODE